_target_: lightning.pytorch.trainer.Trainer

default_root_dir: ${paths.output_dir}

min_epochs: 1   # 保证训练至少进行的轮数
max_epochs: 1000

accelerator: gpu  # 指定用于训练的硬件加速器。 mps 代表 Apple Silicon (M1/M2/M3) 的 Metal Performance Shaders。
devices: 1  # 指定使用的设备数量。 1 表示使用 1 个设备。

# mixed precision for extra speed-up  设置训练的数值精度
# precision: 16

# perform a validation loop every N training epochs
# 指定每隔多少个训练 epoch 运行一次验证集（validation loop）。 1 表示每个 epoch 结束后都进行一次验证。
check_val_every_n_epoch: 10

# set True to to ensure deterministic results
# makes training slower but gives more reproducibility than just setting seeds
# 控制训练过程是否是确定性的。如果设置为 True ，PyTorch Lightning 会尝试控制所有随机性来源，使得每次运行代码都能得到完全相同的结果。
# false更快，true慢
deterministic: False
